apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  selector:
    app.kubernetes.io/name: helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
  type: LoadBalance